### PR TITLE
resources add and scaffolding complete

### PR DESCRIPTION
**Pull request by mtallentb**
### Pull Requests

When you submit a pull request to the project repository, it should provide all of the information necessary for one of your teammates to verify its completeness.

#### Descriptions

Added resources for each table in ERD. Created models corresponding to each resource.
Created Customers controller for GET, POST, PUT.

#### Steps to Test

Review Models and Controllers

rails routes

#### Link to Feature Ticket

n/a

### CODE REVIEW

**Review by tedpennington — APPROVED** [review]
Sure

**Review by daniel-certa-1228 — APPROVED** [review]
It was better than "Cats".

**Comment by palmierie** [comment]
git r done, Chudley! 👍

**Comment by hiattcollins** [comment]
TWO CHUD THUMBS UP

**Pull request merged**
